version: "3.8"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./plugins/elementor:/var/www/html/wp-content/plugins/elementor
      - ./plugins/elementor-pro:/var/www/html/wp-content/plugins/elementor-pro
      - ./themes:/var/www/html/wp-content/themes/hello-elementor-theme
      - ./themes:/var/www/html/wp-content/themes/hello-elementor-child-theme
      - ./uploads:/var/www/html/wp-content/uploads

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: